// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC58WYExbsvoEkTvaMe-KcIueolemVge5c',
    appId: '1:56446072383:web:80dc168b055eb68a43aa8a',
    messagingSenderId: '56446072383',
    projectId: 'cv-craft-91e54',
    authDomain: 'cv-craft-91e54.firebaseapp.com',
    storageBucket: 'cv-craft-91e54.firebasestorage.app',
    measurementId: 'G-ZDM0R1WNPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGK252-7W5exW74VupONaycXj-SVIYBkE',
    appId: '1:56446072383:android:f9d672c5be0e012e43aa8a',
    messagingSenderId: '56446072383',
    projectId: 'cv-craft-91e54',
    storageBucket: 'cv-craft-91e54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUguzDZhFFaCI1E2y1kZwegWkzd4duLPk',
    appId: '1:56446072383:ios:1167a0de7baf969743aa8a',
    messagingSenderId: '56446072383',
    projectId: 'cv-craft-91e54',
    storageBucket: 'cv-craft-91e54.firebasestorage.app',
    iosBundleId: 'com.sulemanlabs.cvcraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUguzDZhFFaCI1E2y1kZwegWkzd4duLPk',
    appId: '1:56446072383:ios:a9b32c84d995808743aa8a',
    messagingSenderId: '56446072383',
    projectId: 'cv-craft-91e54',
    storageBucket: 'cv-craft-91e54.firebasestorage.app',
    iosBundleId: 'com.example.cvMaker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC58WYExbsvoEkTvaMe-KcIueolemVge5c',
    appId: '1:56446072383:web:9f89361af49550d443aa8a',
    messagingSenderId: '56446072383',
    projectId: 'cv-craft-91e54',
    authDomain: 'cv-craft-91e54.firebaseapp.com',
    storageBucket: 'cv-craft-91e54.firebasestorage.app',
    measurementId: 'G-PWPLMMVC90',
  );
}
